### ISSUE TITLE
Mismatch between file name and name of public class

### ISSUE THREAD

**Issue by yfcai** [seba--/sugarj#16]
Say the file Syntax.sugj contains
public sugar Sugar { ... }.
Instead of an error, the following files are generated:

Syntax.dep
Syntax.gen
Sugar.sdf
Sugar.str

**Comment by seba--** [comment]
At least now there is an error message indicating a mismatching declaration name.

The file generation is intended behavior.
- The first 2 files represent compile information that is used by the compiler internally.
- The last 2 files represent the compiled artifacts of the declaration "Sugar".
