### ISSUE TITLE
Non-hierarchical SugarHaskell modules

### ISSUE THREAD

**Issue by Toxaris** [seba--/sugarj#4]
SugarJ complains about the file `Text.shs` with the following content:

``` haskell
module Test where

main = putStrLn "hello world"
```

The error is annotated to the `module` keyword: The declared namespace 'Test' does not match the expected namespace 'Test.shs'.

SugarJ should accept this file.

**Comment by seba--** [comment]
fixed df0547d92ce004824d99e92cf00a4b6c26b1306d 0e579cb70e3c0a9a44f10a6d9ef11d8793545deb
