### ISSUE TITLE
Wrong suffix for desugared AST

### ISSUE THREAD

**Issue by dpeuscher** [seba--/sugarj#49]
The desugared generated AST is saved with the suffix ".desug". Therefore it won't be opened in an aterm-editor.

**Comment by seba--** [comment]
Fixed [here](https://github.com/sugar-lang/stdlib/commit/48b1ed89365941fc9a99182a0bfc740619536d16)

**Comment by seba--** [comment]
You will need to delete the .sugarjcache to activate the change.
