### ISSUE TITLE
Parser does not handle @Override-Annotation

### ISSUE THREAD

**Issue by dpeuscher** [seba--/sugarj#51]
When you annotate a method-overwrite in Java, the parser issues an Error.

**Comment by seba--** [comment]
I cannot confirm this; works fine for me. Are you sure it's not some other syntax error?

![screen shot 2013-11-08 at 09 03 22](https://f.cloud.github.com/assets/731053/1499019/478da700-484c-11e3-969e-a4285171069e.png)

**Comment by dpeuscher** [comment]
Sorry, mistook it for lack of annotations for static methods in java. Not a bug (in sugarJ).
