### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by OriRoth** [seba--/sugarj#53]
The update site `http://update.sugarj.org` seems to be down and the binaries `http://sugarj.org/binaries/` could not be found. Is this project still supported? Did the update site migrated? Are there any available binaries/plugins? What are my best options if if I want to run *SugarJ*? Thanks in advance.

**Comment by seba--** [comment]
You can find a mirror of the update site here http://www.erdweg.org/projects/sugarj/update/index.html . Note that we are not developing or maintaining this project at the moment.
