### ISSUE TITLE
Provide compiler-only SugarJ installation

### ISSUE THREAD

**Issue by seba--** [seba--/sugarj#7]
Currently, the SugarJ compiler depends on lots of Java classes from various Eclipse (sub)project. In order to provide a small binary installation of SugarJ that does not include Eclipse, this dependency should be decoupled. That is, the SugarJ compiler should not depend on any Eclipse resource.

**Comment by Blaisorblade** [comment]
Isn't this essentially solved by now?

**Comment by seba--** [comment]
True. @yfcai developed an extraction tool that collects the necessary class files for running the SugarJ compiler without (full) Eclipse. See [cli-scripts](http://github.com/seba--/sugarj/tree/master/deployment/cli-scripts).
